### PR TITLE
fix(trashbin): context menu label not updating

### LINKED ISSUE #3743: Text on Trashbin buttons doesn't change after an item has been added
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.85.519.g549a528b
- Spicetify version: v2.42.14
```

### 📝 Description

1. Place an Artist/Track in the Trashbin
2. Right Click on the same item

### 📸 Screenshots

https://github.com/user-attachments/assets/3c5d70f0-a3ef-4c07-9255-400466b40a9e

### PR DESCRIPTION
**Pull request by yetval**
\`shouldAddContextMenu\` used \`this.name\` to update the context menu label, but \`this\` is no longer bound to the \`ContextMenu.Item\` in newer Spicetify versions. Referencing \`cntxMenu\` directly via closure fixes the stale label.

Fixes #3743

## Summary by CodeRabbit

* **Bug Fixes**
  * Corrected context-menu labeling in the trashbin extension so menu items display and reference the proper label for track and artist entries.

### CODE REVIEW

File: Extensions/trashbin.js [hunk 1]
```diff
@@ -342,19 +342,19 @@
...
-			this.name = trashArtistList[uri] ? UNTHROW_TEXT : THROW_TEXT;
+			cntxMenu.name = trashArtistList[uri] ? UNTHROW_TEXT : THROW_TEXT;
 			return true;
 		}
 
 		return false;
 	}
 
-	const cntxMenu = new Spicetify.ContextMenu.Item(THROW_TEXT, toggleThrow, shouldAddContextMenu, trashbinIcon);
+	let cntxMenu = new Spicetify.ContextMenu.Item(THROW_TEXT, toggleThrow, shouldAddContextMenu, trashbinIcon);
```
Comment (rxri) [inline Extensions/trashbin.js]: cntxMenu is an object.

```suggestion
	const cntxMenu = new Spicetify.ContextMenu.Item(THROW_TEXT, toggleThrow, shouldAddContextMenu, trashbinIcon);
```

Comment (yetval) [reply Extensions/trashbin.js]: Thank You!

**Review by rxri — APPROVED** [review]
