### PR TITLE
fix(shuffle+): lower limit & bring back `queryArtistOverview`

### LINKED ISSUE #3000: [shuffle+] cannot shuffle artist page
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663.gb699649e
- Spicetify version: 2.36.9
```

### 📝 Description

Shuffle+ gives this error when trying to launch it from the Artist Page. 
Shuffle+ from the playlist/mix works fine.

### 📸 Screenshots

image

### PR DESCRIPTION
**Pull request by rxri**
Fixes #3000

### CODE REVIEW

**Review by theRealPadster — APPROVED** [review]

File: Extensions/shuffle+.js [hunk 1]
```diff
@@ -368,7 +368,13 @@
 	}
 
 	async function fetchArtistTracks(uri) {
-		const { queryArtistDiscographyAll, queryArtistOverview } = Spicetify.GraphQL.Definitions;
+		const { queryArtistDiscographyAll } = Spicetify.GraphQL.Definitions;
+		const queryArtistOverview = {
+			name: "queryArtistOverview",
+			operation: "query",
+			sha256Hash: "35648a112beb1794e39ab931365f6ae4a8d45e65396d641eeda94e4003d41497",
```
Comment (afonsojramos) [inline Extensions/shuffle+.js:375]: Where is this coming from?

Comment (rxri) [reply Extensions/shuffle+.js:375]: It's the definition coming from older spotify version which is not present in newer ones

Comment (afonsojramos) [reply Extensions/shuffle+.js:375]: Let's leave a comment to document that!

**Review by afonsojramos — APPROVED** [review]
