### PR TITLE
fix(lyrics): switch to `wg://` protocol

### LINKED ISSUE #1566: Spotify Lyrics seems to be not working (Lyrics Plus and Popup)
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version: 2.8.4
```

### 📝 Description

Even if Spotify is the first option on my Lyrics Plus, my client always retrieves Netease lyrics instead. I also tried disabling all the options but Spotify, but the result is as you see in the screenshots.
The only difference is that Popup Lyrics shows "No lyric".

### 📸 Screenshots

image
image
image

### PR DESCRIPTION
**Pull request by ririxidev**
* fix: change protocol to wg://
  * Fixes issues with getting spotify lyrics on lyrics-plus & popupLyrics
  * Adds @ts-nocheck on popupLyrics
* style: change wording when no lyrics

Fixes #1566

### CODE REVIEW

**Comment by th3an7** [comment]
Hey,
How did you find about that new `wg://` protocol? I'm curious if there are any new endpoints or if they just moved old `hm://` without adding anything...

**Comment by ririxidev** [comment]
> Hey,
> 
> How did you find about that new `wg://` protocol? I'm curious if there are any new endpoints or if they just moved old `hm://` without adding anything...

Someone said in linked issue that after changing to wg:// protocol it works, and it actually does so idk how they found it.

File: Extensions/popupLyrics.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// @ts-check
+// @ts-nocheck
```
Comment (afonsojramos) [inline Extensions/popupLyrics.js:1]:
```suggestion
// @ts-check
```

I'm not sure why you removed it, but you should get minimal errors with the check. Some are miscategorized, we are aware, but what you get from the `check` is more than what you'll get by just having it disabled.

**Review by afonsojramos — CHANGES_REQUESTED** [review]
Looking good, just take a look at the requested changes. Sorry for the delay, Easter 🐰🥚 got in the way!

File: Extensions/popupLyrics.js (hunk 1 above)
Comment (ririxidev) [reply Extensions/popupLyrics.js:1]: I would love to but it throws error that I can't fix since it's about types. This file isn't typescript one so I can't add types.

Comment (ririxidev) [reply Extensions/popupLyrics.js:1]: Having typescript check in JavaScript file isn't ideal and shouldn't be done at all because of errors. Typescript is for types, not for no having them and only using it for example "this return statement isn't going to work" etc etc. If you really need it I can simply add typescript file that will generate JavaScript dist

File: Extensions/popupLyrics.js [hunk 2]
```diff
@@ -1,4 +1,3 @@
-// @ts-check
```
Comment (afonsojramos) [inline Extensions/popupLyrics.js:1]:
```suggestion
```

My bad here!

**Review by afonsojramos — CHANGES_REQUESTED** [review]

**Review by afonsojramos — APPROVED** [review]
